name: curl_impersonate_dart_example
description: An example app demonstrating the browser impersonation client.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  curl_impersonate_dart:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
